# -*- coding: utf-8 -*-
"""rockgame1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Lbh8i5pSgWhIyQkdX6XMTcKB8ShJXQU
"""

# Import necessary libraries
import random
from IPython.display import clear_output
from termcolor import colored

# Function to display the game title
def display_title():
    print(colored("Welcome to Rock-Paper-Scissors!", "blue", attrs=["bold"]))
    print(colored("=============================", "blue"))

# Function to get the player's choice
def get_player_choice():
    choice = input(colored("Enter your choice (rock, paper, scissors): ", "yellow"))
    while choice.lower() not in ["rock", "paper", "scissors"]:
        print(colored("Invalid choice! Please try again.", "red"))
        choice = input(colored("Enter your choice (rock, paper, scissors): ", "yellow"))
    return choice.lower()

# Function to get the computer's choice
def get_computer_choice():
    return random.choice(["rock", "paper", "scissors"])

# Function to determine the winner
def determine_winner(player_choice, computer_choice):
    if player_choice == computer_choice:
        return colored("It's a tie!", "magenta")
    elif (player_choice == "rock" and computer_choice == "scissors") or \
         (player_choice == "paper" and computer_choice == "rock") or \
         (player_choice == "scissors" and computer_choice == "paper"):
        return colored("You win!", "green")
    else:
        return colored("Computer wins!", "red")

# Function to display the result
def display_result(player_choice, computer_choice, result):
    print(colored(f"\nYour choice: {player_choice}", "cyan"))
    print(colored(f"Computer's choice: {computer_choice}", "cyan"))
    print(colored(f"Result: {result}\n", "cyan"))

# Main function to run the game
def play_game():
    display_title()
    while True:
        player_choice = get_player_choice()
        computer_choice = get_computer_choice()
        result = determine_winner(player_choice, computer_choice)
        display_result(player_choice, computer_choice, result)

        play_again = input(colored("Do you want to play again? (yes/no): ", "yellow"))
        if play_again.lower() != "yes":
            print(colored("Thanks for playing! Goodbye!", "blue"))
            break
        clear_output(wait=True)

# Run the game
play_game()